version: 2

models:
  - name: stg_trips
    columns:
      - name: trip_id
        tests:
          - not_null
          - unique
      - name: driver_id
        tests:
          - not_null
      - name: passenger_id
        tests:
          - not_null
      - name: start_time
        tests:
          - not_null
      - name: end_time
        tests:
          - not_null
      - name: distance_km
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 10, 15, 20, 25, 30]  # optional sanity ranges
      - name: fare
        tests:
          - not_null
          - relationships:
              to: ref('stg_drivers')
              field: driver_id

  - name: stg_drivers
    columns:
      - name: driver_id
        tests:
          - not_null
          - unique
      - name: rating
        tests:
          - not_null
          - accepted_values:
              values: [4.5, 4.6, 4.7, 4.8, 4.9, 5.0]

  - name: stg_passengers
    columns:
      - name: passenger_id
        tests:
          - not_null
          - unique
      - name: rating
        tests:
          - not_null
          - accepted_values:
              values: [4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0]
